version: '3'
services:
  mqttserver:
    build: .
    container_name: "fpm-iot-cloud-mqtt-server"
    volumes:
      - ./source:/app/source
      - ./config.json:/app/config.json
    ports:
      - "2883:1883"
    environment:
      MQTT_DEBUG: 0
      MQTT_AUTH: '{"admin":"123123123"}'
    networks:
      - mqtt-network
    restart: always
networks:
  mqtt-network: