version: '3'
services:
  web:
    build: .
    volumes:
      - ./source:/app/source
    ports:
      - "1883:1883"
      - "9992:9999"
    networks: 
      - staging-network
networks:
  staging-network: 
